/* 
     A C-program for MT19937, with initialization improved 2002/1/26.
     Coded by Takuji Nishimura and Makoto Matsumoto.

     Before using, initialize the state by using init_genrand(seed)    
     or init_by_array(init_key, key_length).

     Copyright (C) 1997 - 2002, Makoto Matsumoto and Takuji Nishimura,
     All rights reserved.                            

     Redistribution and use in source and binary forms, with or without
     modification, are permitted provided that the following conditions
     are met:

     1. Redistributions of source code must retain the above copyright
        notice, this list of conditions and the following disclaimer.

     2. Redistributions in binary form must reproduce the above copyright
        notice, this list of conditions and the following disclaimer in the
        documentation and/or other materials provided with the distribution.

     3. The names of its contributors may not be used to endorse or promote 
        products derived from this software without specific prior written 
        permission.

     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
     "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
     LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
     A PARTICULAR PURPOSE ARE DISCLAIMED.    IN NO EVENT SHALL THE COPYRIGHT OWNER OR
     CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
     EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
     PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
     PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
     LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
     NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.


     Any feedback is very welcome.
     http://www.math.sci.hiroshima-u.ac.jp/~m-mat/MT/emt.html
     email: m-mat @ math.sci.hiroshima-u.ac.jp (remove space)
*/

#include "corefw.h" // IWYU pragma: keep
#include "CFRandom.h"
#include <string.h>

/* Period parameters */
#define MT19937_N 624
#define MT19937_M 397
#define MT19937_MATRIX_A 0x9908b0dfUL /* constant vector a */
#define MT19937_UPPER_MASK 0x80000000UL /* most significant w-r bits */
#define MT19937_LOWER_MASK 0x7fffffffUL /* least significant r bits */

static CFRandomRef CFRandomInstance = nullptr;

static inline void init_genrand(CFRandomRef this, unsigned long s);
static inline void init_by_array(CFRandomRef this, unsigned long init_key[], unsigned long key_length);
static inline unsigned long genrand_int32(CFRandomRef this);
static inline double genrand_real1(CFRandomRef this);

class(CFRandom);

unsigned long frameCounter = 999;

/**
 * @brief Generates the next pseudo-random unsigned long value.
 *
 * If the random number generator instance (`CFRandomInstance`) is not initialized,
 * it will be created using the current value of `frameCounter` as the seed.
 * The function then returns a new pseudo-random number generated by `genrand_int32`.
 *
 * @return The next pseudo-random unsigned long value.
 */
proc unsigned long NextLong(void)
{
    if (CFRandomInstance == nullptr) {
        // unsigned long seed = (unsigned long)time(nullptr);
        unsigned long seed = frameCounter;
        CFRandomInstance = NewRandom(seed);
    }

    return genrand_int32(CFRandomInstance);
}

/**
 * @brief Generates the next pseudo-random double value in the range [0, 1].
 *
 * If the random number generator instance (`CFRandomInstance`) is not initialized,
 * it initializes it using a seed value (`frameCounter`). The function then returns
 * a pseudo-random double value generated by `genrand_real1`.
 *
 * @return A pseudo-random double value in the range [0, 1].
 */
proc double NextDouble(void)
{
    if (CFRandomInstance == nullptr) {
        // unsigned long seed = (unsigned long)time(nullptr);
        unsigned long seed = frameCounter;
        CFRandomInstance = NewRandom(seed);
    }
    return genrand_real1(CFRandomInstance);
}

/**
 * @brief Constructor function for CFRandom objects.
 *
 * Initializes a new random number generator instance using the current frame counter
 * as the seed value. This function is intended to be called when creating a new
 * CFRandom object.
 *
 * @param this Pointer to the CFRandom object being constructed.
 * @return Pointer to the newly created random number generator instance.
 */
proc void* Ctor(CFRandomRef this)
{
    // (CFRandomRef)this;
    // return New(this, (unsigned long)time(nullptr));
    return NewRandom(frameCounter);
}

/**
 * @brief Constructor function for the CFRandom object.
 *
 * Initializes the internal state of the CFRandom object using the provided seed.
 * This function zeroes out the internal MT19937 state array, sets the initial
 * index, and seeds the random number generator.
 *
 * @param this Pointer to the CFRandom object to initialize.
 * @param seed The seed value to initialize the random number generator.
 * @return Pointer to the initialized CFRandom object.
 */
proc void* Ctor(CFRandomRef this, unsigned long seed)
{
    memset(this->mt, 0, (MT19937_N * sizeof(unsigned long)));
    this->mti = MT19937_N + 1;
    init_genrand(this, seed);
    return this;
}

/**
 * @brief Constructor for the CFRandom object, initializes the random number generator state.
 *
 * This function initializes the internal state of the CFRandom object using the provided seed array.
 * It clears the internal state array, sets the initial index, and seeds the generator using the
 * specified seed values.
 *
 * @param this Pointer to the CFRandom object to initialize.
 * @param seed Array of unsigned long values to use as the seed.
 * @param length Number of elements in the seed array.
 * @return Pointer to the initialized CFRandom object.
 */
proc void* Ctor(CFRandomRef this, unsigned long seed[], int length)
{
    memset(this->mt, 0, (MT19937_N * sizeof(unsigned long)));
    this->mti = MT19937_N + 1;
    init_by_array(this, seed, (unsigned long)length);
    return this;
}

/**
 * @brief Initializes the internal state array for the Mersenne Twister random number generator.
 *
 * This function seeds the Mersenne Twister (MT19937) generator with the given seed value `s`.
 * It fills the internal state array `mt` of the CFRandomRef structure according to the algorithm
 * described by Makoto Matsumoto and Takuji Nishimura. The initialization ensures that the entire
 * state array is affected by the seed, improving randomness.
 *
 * @param this Pointer to a CFRandomRef structure containing the state array and index.
 * @param s    The seed value used to initialize the generator.
 *
 * @note The multiplier 1812433253UL is recommended by Knuth (TAOCP Vol2, 3rd Ed., p.106).
 * @note This function is intended for internal use and assumes that `this` is valid and
 *       that `mt` has space for MT19937_N elements.
 */
static inline void init_genrand(CFRandomRef this, unsigned long s)
{
    this->mt[0] = s & 0xffffffffUL;
    for (this->mti = 1; this->mti < MT19937_N; this->mti++) {
        this->mt[this->mti] = (1812433253UL * (this->mt[this->mti - 1] ^ (this->mt[this->mti - 1] >> 30)) + this->mti);
        /* See Knuth TAOCP Vol2. 3rd Ed. P.106 for multiplier. */
        /* In the previous versions, MSBs of the seed affect     */
        /* only MSBs of the array this->mt[].                        */
        /* 2002/01/09 modified by Makoto Matsumoto             */
        this->mt[this->mti] &= 0xffffffffUL;
        /* for >32 bit machines */
    }
}

/**
 * @brief Initializes the internal state array of the Mersenne Twister PRNG using an array of keys.
 *
 * This function seeds the Mersenne Twister (MT19937) random number generator with an array of
 * unsigned long values. It first initializes the generator with a fixed seed, then mixes in the
 * provided key array to further randomize the state. The process ensures that the internal state
 * is well-scrambled and suitable for generating high-quality pseudorandom numbers.
 *
 * @param this      Pointer to the CFRandomRef structure containing the MT state array.
 * @param init_key  Array of unsigned long values used as the seed key.
 * @param key_length Number of elements in the init_key array.
 *
 * @note This function is based on the reference implementation of the MT19937 algorithm.
 *       It is intended for internal use and assumes that the state array and constants
 *       (such as MT19937_N) are properly defined.
 */
static inline void init_by_array(CFRandomRef this, unsigned long init_key[], unsigned long key_length)
{
    unsigned long i, j, k;
    init_genrand(this, 19650218UL);
    i = 1;
    j = 0;
    k = (MT19937_N > key_length ? MT19937_N : key_length);
    for (; k; k--) {
        this->mt[i] = (this->mt[i] ^ ((this->mt[i - 1] ^ (this->mt[i - 1] >> 30)) * 1664525UL))
            + init_key[j] + j; /* non linear */
        this->mt[i] &= 0xffffffffUL; /* for WORDSIZE > 32 machines */
        i++;
        j++;
        if (i >= MT19937_N) {
            this->mt[0] = this->mt[MT19937_N - 1];
            i = 1;
        }
        if (j >= key_length)
            j = 0;
    }
    for (k = MT19937_N - 1; k; k--) {
        this->mt[i] = (this->mt[i] ^ ((this->mt[i - 1] ^ (this->mt[i - 1] >> 30)) * 1566083941UL))
            - i; /* non linear */
        this->mt[i] &= 0xffffffffUL; /* for WORDSIZE > 32 machines */
        i++;
        if (i >= MT19937_N) {
            this->mt[0] = this->mt[MT19937_N - 1];
            i = 1;
        }
    }

    this->mt[0] = 0x80000000UL; /* MSB is 1; assuring non-zero initial array */
}

/**
 * @brief Generates a 32-bit pseudo-random integer using the Mersenne Twister algorithm.
 *
 * This function produces a pseudo-random unsigned long integer based on the internal state
 * of the provided CFRandomRef object. If the state has not been initialized, it will be
 * seeded with a default value. The function updates the internal state as needed and applies
 * tempering to improve the statistical properties of the output.
 *
 * @param this Pointer to a CFRandomRef structure containing the generator's state.
 * @return A 32-bit pseudo-random unsigned long integer.
 */
static inline unsigned long genrand_int32(CFRandomRef this)
{
    unsigned long y;
    static unsigned long mag01[2] = { 0x0UL, MT19937_MATRIX_A };
    /* mag01[x] = x * MT19937_MATRIX_A    for x=0,1 */

    if (this->mti >= MT19937_N) { /* generate MT19937_N words at one time */
        int kk;

        if (this->mti == MT19937_N + 1) /* if init_genrand() has not been called, */
            init_genrand(this, 5489UL); /* a default initial seed is used */

        for (kk = 0; kk < MT19937_N - MT19937_M; kk++) {
            y = (this->mt[kk] & MT19937_UPPER_MASK) | (this->mt[kk + 1] & MT19937_LOWER_MASK);
            this->mt[kk] = this->mt[kk + MT19937_M] ^ (y >> 1) ^ mag01[y & 0x1UL];
        }
        for (; kk < MT19937_N - 1; kk++) {
            y = (this->mt[kk] & MT19937_UPPER_MASK) | (this->mt[kk + 1] & MT19937_LOWER_MASK);
            this->mt[kk] = this->mt[kk + (MT19937_M - MT19937_N)] ^ (y >> 1) ^ mag01[y & 0x1UL];
        }
        y = (this->mt[MT19937_N - 1] & MT19937_UPPER_MASK) | (this->mt[0] & MT19937_LOWER_MASK);
        this->mt[MT19937_N - 1] = this->mt[MT19937_M - 1] ^ (y >> 1) ^ mag01[y & 0x1UL];

        this->mti = 0;
    }

    y = this->mt[this->mti++];

    /* Tempering */
    y ^= (y >> 11);
    y ^= (y << 7) & 0x9d2c5680UL;
    y ^= (y << 15) & 0xefc60000UL;
    y ^= (y >> 18);

    return y;
}

/**
 * @brief Generates a random 31-bit signed integer.
 *
 * This function calls genrand_int32 to generate a 32-bit random integer,
 * then shifts the result right by 1 bit to obtain a 31-bit non-negative integer.
 *
 * @param this Pointer to the CFRandomRef random number generator instance.
 * @return A random 31-bit signed integer (non-negative).
 */
static inline long genrand_int31(CFRandomRef this)
{
    return (long)(genrand_int32(this) >> 1);
}

/**
 * @brief Generates a random double value in the range [0, 1].
 *
 * This function uses the underlying 32-bit random integer generator
 * and scales its output to produce a double-precision floating-point
 * value uniformly distributed in the closed interval [0, 1].
 *
 * @param this Reference to the CFRandom instance.
 * @return A random double value in the range [0, 1].
 */
static inline double genrand_real1(CFRandomRef this)
{
    return (double)genrand_int32(this) * (1.0 / 4294967295.0);
    /* divided by 2^32-1 */
}

/**
 * @brief Generates a random double-precision floating-point number in the range [0, 1).
 *
 * This function uses the underlying 32-bit integer random number generator
 * and scales the result to produce a double in the half-open interval [0, 1).
 *
 * @param this Pointer to the CFRandomRef random number generator instance.
 * @return A random double value in the range [0, 1).
 */
static inline double genrand_real2(CFRandomRef this)
{
    return (double)genrand_int32(this) * (1.0 / 4294967296.0);
    /* divided by 2^32 */
}

/**
 * @brief Generates a random double in the interval [0,1).
 *
 * This function produces a pseudo-random double-precision floating-point number
 * in the range [0, 1), using the underlying 32-bit integer generator.
 * The result is computed by adding 0.5 to the generated integer and dividing by 2^32.
 *
 * @param this Pointer to the CFRandomRef random number generator instance.
 * @return A double value uniformly distributed in the interval [0, 1).
 */
static inline double genrand_real3(CFRandomRef this)
{
    return (((double)genrand_int32(this)) + 0.5) * (1.0 / 4294967296.0);
    /* divided by 2^32 */
}

/**
 * @brief Generates a random double-precision floating-point number in the interval [0, 1).
 *
 * This function uses two 32-bit random integers, shifts and combines them to produce
 * a 53-bit precision random value, which is then scaled to the [0, 1) range.
 *
 * @param this Pointer to a CFRandomRef structure used as the random number generator state.
 * @return A double-precision floating-point number uniformly distributed in [0, 1).
 */
static inline double genrand_res53(CFRandomRef this)
{
    unsigned long a = genrand_int32(this) >> 5, b = genrand_int32(this) >> 6;
    return ((double)a * 67108864.0 + (double)b) * (1.0 / 9007199254740992.0);
}

/* These real versions are due to Isaku Wada, 2002/01/09 added */
